name: tipsmart
description: "Football betting tips flutter app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  envied: ^0.5.4+1
  email_validator: ^3.0.0
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_analytics: ^11.2.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.2.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  cached_network_image: ^3.4.0
  dio: ^5.5.0+1
  intl: ^0.19.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  package_info_plus: ^8.0.1
  gap: ^3.0.1
  share_plus: ^10.0.0
  fluttertoast: ^8.2.6
  onesignal_flutter: ^5.2.4
  google_mobile_ads: ^5.1.0
  applovin_max: ^3.11.0
  adaptive_theme: ^3.6.0
  google_fonts: ^6.2.1
  dotted_border: ^2.1.0
  uuid: ^4.5.0
  cron: ^0.6.1
  rate_my_app: ^2.2.0
#  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  change_app_package_name: ^1.3.0
  envied_generator: ^0.5.4+1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/app_icon.png

  fonts:
    - family: TipSmartIcons
      fonts:
        - asset: assets/fonts/TipSmartIcons.ttf
